### ISSUE TITLE
Error Running XGDork on kali

### ISSUE THREAD

**Issue by filebe777** [E4rr0r4/XGDork#1]
__  ______ ____    42       _     
  \ \/ / ___|  _ \  ___  _ __| | __ 
   \  / |  _| | | |/ _ \| '__| |/ / 
   /  \ |_| | |_| | (_) | |  |   <  
  /_/\_\____|____/ \___/|_|  |_|\_\ 

 --- ViraX Google Dork Scanner --- 
Original code by ViraX
Version: b0.7.2 for Python 2.7
Contributor(s)
- 

 [!] DISCLAIMER: This program makes it easy to find vulnerable SQL injection URLs, it's a very simple program (naive), I am not responsible for illegal acts that you would do with this program !, only educational . [!] 

it will be improved, wait ...

 [!] XGDork Start ... [!] 

From cffi callback <function _verify_callback at 0x7f62d472fcf8>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
 [!] IP Public Error 

 [*] Public IP overview: NULL
 [*] GSE Crawling wait ...

 [+] User-Agent: Mozilla/5.0 (X11; U; Linux i686; de; rv:1.8.1.1) Gecko/20061220 Firefox/2.0.0.1 (Swiftfox)
From cffi callback <function _verify_callback at 0x7f62d472fe60>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
Traceback (most recent call last):
  File "XGDork.py", line 124, in <module>
    search_engine (data_dork, data_page, data_file, data_bypass, data_cdom)
  File "/root/Desktop/XGDork/XGDlib.py", line 379, in search_engine
    greq = requests.get(nurl, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 519, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
root@kali:~/Desktop/XGDork#

**Comment by filebe777** [comment]
No response from you yet?

**Comment by E4rr0r4** [comment]
it can come from a lot of things ...
on my side I never had this problem, is the problem fixed since ?

if not,
1 / modify the code, simple,
- go to XGDlib.py,
- go to the 'search_engine' method (function)
- modify requests.get (), add 'verify = False'
- save and re-launch

2 / what is your version openssl ? others ?
  .. update your system or check for conflicts

sorry bro', I have no idea in mind for the moment .... let me know !

**Comment by filebe777** [comment]
still thesame error

root@kali:~/Desktop/XGDork# python2 XGDork.py -d 'shop.php?do=part&id=' -p '20' -o 'out_file'



  __  ______ ____    42       _     
  \ \/ / ___|  _ \  ___  _ __| | __ 
   \  / |  _| | | |/ _ \| '__| |/ / 
   /  \ |_| | |_| | (_) | |  |   <  
  /_/\_\____|____/ \___/|_|  |_|\_\ 

  --- ViraX Google Dork Scanner --- 

Original code by ViraX
Version: b0.9.0 for Python 2.7
Compatible for Android (NoRoot) - Termux 

Contributor(s)/Source(s)
- SQLmap ('agents file') - https://github.com/sqlmapproject/ 
- 


 [!] DISCLAIMER: A simple 'naive' tool to find SQLi Vulnerable websites in the wild via Google, I am not responsible for illegal acts that you would do with this program !, only educational . [!] 

 [*] it will be improved, wait ...

 [!] XGDork Start [Fri Sep 21 18:18:52 2018] ... [!] 

 [*] let's try with [ shop.php?do=part&id= ] Happy hunting ! ;) 
From cffi callback <function _verify_callback at 0x7f3023da10c8>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
 [!] IP Public Error 

 [*] Public IP overview: NULL

 [*] GSE Crawling wait ...

 [<S 0-0>] 
 [+] User-Agent: Mozilla/5.0 (X11; U; Linux x86_64; zh-TW; rv:1.9.0.13) Gecko/2009080315 Ubuntu/9.04 (jaunty) Firefox/3.0.13
From cffi callback <function _verify_callback at 0x7f3023da1230>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
Traceback (most recent call last):
  File "XGDork.py", line 171, in <module>
    search_engine (data_dork, data_page, data_file, data_bypass, data_cdom, data_forcing, data_timeout)
  File "/root/Desktop/XGDork/XGDlib.py", line 599, in search_engine
    greq = requests.get(nurl, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 524, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

**Comment by opg1313** [comment]
I get this one; 

root@kali:~/XGDork# python XGDork.py -d "index.php?id=" -p 4 -o outfile



  __  ______ ____    42       _     
  \ \/ / ___|  _ \  ___  _ __| | __ 
   \  / |  _| | | |/ _ \| '__| |/ / 
   /  \ |_| | |_| | (_) | |  |   <  
  /_/\_\____|____/ \___/|_|  |_|\_\ 

  --- ViraX Google Dork Scanner --- 

  Original code by ViraX
  Version: final-1.0k FreeSoftware for Python 2.7
  Compatible Mobile - Android (NoRoot) - Termux 

  Contributor(s)/Source(s)
  - SQLmap ('agents file') - https://github.com/sqlmapproject/ 
  - 


 [!] DISCLAIMER: A simple 'naive' tool to find SQLi Vulnerable websites in the wild via Google.
 I am not responsible for illegal acts that you would do with this program !, only educational . [!] 


 [!] XGDork Start [Mon Aug 12 11:15:27 2019] ... [!] 

 [*] let's try with [ index.php?id= ] Happy hunting ! ;) 

 [*] Public IP overview: <
 [*] GSE Crawling wait ...

 [<Serial 1>] 
 [+] User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.2 (KHTML, like Gecko) Chrome/22.0.1216.0 Safari/537.2
Traceback (most recent call last):
  File "XGDork.py", line 218, in <module>
    search_engine (data_dork, data_page, data_file, data_bypass, data_cdom, data_forcing, data_timeout, data_inject, data_mores)
  File "/root/XGDork/XGDlib.py", line 771, in search_engine
    greq = requests.get(nurl, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/safe_mode.py", line 39, in wrapped
    return function(method, url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 51, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 241, in request
    r.send(prefetch=prefetch)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 641, in send
    raise SSLError(e)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

**Comment by Flywhiter** [comment]
> it can come from a lot of things ...
> on my side I never had this problem, is the problem fixed since ?
> 
> if not,
> 1 / modify the code, simple,
> 
> * go to XGDlib.py,
> * go to the 'search_engine' method (function)
> * modify requests.get (), add 'verify = False'
> * save and re-launch
> 
> 2 / what is your version openssl ? others ?
>   .. update your system or check for conflicts
> 
> sorry bro', I have no idea in mind for the moment .... let me know !

thks it work for my kali
